# Generated by Django 2.0.4 on 2018-08-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='loc_201882717473308eaebf9', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='sta_2018827174733eedca23e', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
