# Generated by Django 2.0.4 on 2018-08-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='id',
            field=models.CharField(default='route_2018828183430cb585653', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='id',
            field=models.CharField(default='route_20188281834306bbb857d', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
